name: daily_update
on:
  schedule:
    - cron: '5 10 * * *'      # 北京时间 18:05
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run python daily_update.py
        run: python daily_update.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PERIOD_TYPE: '1min' # 在这里定义周期类型字符串
